# Generated by Django 3.2 on 2022-08-31 11:32

from django.db import migrations
from random import choice


def forwards_func_lesson(apps, schema_editor):
    Сorses = apps.get_model("mainapp", "Courses")
    corses_id = [i.pk for i in Сorses.objects.all()]

    # Get model
    Lesson = apps.get_model("mainapp", "Lesson")
    # Create model's objects
    for i_course in range(8):
        for i_lesson in range(8):
            Lesson.objects.create(
                course=Сorses.objects.get(pk=choice(corses_id)),
                num=i_lesson,
                title="Какое то описание урока",
                description="Python предназначен для разработки и изучения новых приложений. \
                    Мы предлагаем непросто изучить новый язык программирования, но и научиться применять его на практике. \
                    Этот курс полезен не только тем, кто хочет научиться программировать, но и всем тем, кому не хватает \
                    времени на выполнение практических заданий, а также тем, у кого нет возможности посещать курсы. \
                    Курс состоит из 7 встреч — одно занятие в неделю длительностью 3 часа.\r\nВстречи \
                    проводятся по воскресеньям с 14:00.",
            )


def reverse_func_lesson(apps, schema_editor):
    # Get model
    lesson = apps.get_model("mainapp", "Lesson")
    # Delete objects
    lesson.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [('mainapp', '0003_coursesmigration')]

    operations = [migrations.RunPython(forwards_func_lesson, reverse_func_lesson)]
